# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-10-31 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='score',
            field=models.IntegerField(null=True),
        ),
    ]
